[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
user=root

[program:flask]
command=pdm run python app.py
directory=/workspace/geo_params_web
autostart=true
autorestart=true
startretries=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:streamlit]
command=pdm run python -m streamlit run sl_stats/sl_app.py
directory=/workspace/geo_params_web
autostart=true
autorestart=true
startretries=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
